var MovieService = app.service('MovieService', ['UserNotificationService', function(UserNotificationService) {
    this.getMoviesForBooking = function() {
        var movie = {};
        var movies = [];
        movie.id = 'ET00030170';
        movie.title = 'Rangitaranga';
        movie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00030170.jpg';
        movie.venue = 'Inox Garuda Mall';
        movie.dateShowTime = new Date();
        movie.price = '120';
        movie.booknow = '#/payment/' + movie.id;
        movie.language = 'Kannada';
        movie.genres = ['Adventure', 'Music', 'Mystery'];
        movie.location = 'INOX: Garuda Mall, Magrath Road';
        movie.seatInfo = 'PREMIER';
        movie.screen = 'SCREEN 1';
        movies.push(movie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030171';
        newMovie.title = 'The Conjuring';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00035685.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'English';
        newMovie.genres = ['Horror', 'Mystery', 'Thriller'];
        newMovie.location = 'Innovative Multiplex, Marathahalli';
        newMovie.price = '200';
        newMovie.seatInfo = 'DIAMOND';
        newMovie.screen = 'AUDI 1';
        newMovie.dateShowTime = '17/11/2016 4:25pm';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030172';
        newMovie.title = 'Thithi';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00041598.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'Kannada';
        newMovie.genres = ['Drama'];
        newMovie.location = 'PVR: Orion, Bengaluru';
        newMovie.price = '120';
        newMovie.seatInfo = 'PREMIER';
        newMovie.screen = 'SCREEN 5';
        newMovie.dateShowTime = '19/11/2016 5:30pm';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030173';
        newMovie.title = 'Pink';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00039895.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'Hindi';
        newMovie.genres = ['Drama', 'Thriller'];
        newMovie.location = 'INOX Lido: Off MG Road, Ulsoor ';
        newMovie.price = '180';
        newMovie.seatInfo = 'EXECUTIV';
        newMovie.screen = 'AUDI 2';
        newMovie.dateShowTime = '20-11-2016 10:30am';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030174';
        newMovie.title = 'Ki & Ka';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00035932.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'Hindi';
        newMovie.genres = ['Comedy', 'Romance'];
        newMovie.location = 'PVR: Forum, Bengaluru';
        newMovie.price = '180';
        newMovie.seatInfo = 'EXECUTIV';
        newMovie.screen = 'SCREEN 7';
        newMovie.dateShowTime = '19-11-2016 2:30pm';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030175';
        newMovie.title = 'Rustom';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00035722.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'Hindi';
        newMovie.genres = ['Crime', 'Drama', 'Thriller'];
        newMovie.location = 'Cinepolis: Bannerghatta Road';
        newMovie.price = '180';
        newMovie.seatInfo = 'EXECUTIV';
        newMovie.screen = 'AUDI 6';
        newMovie.dateShowTime = '20-11-2016 9:30pm';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030176';
        newMovie.title = 'Chakravryuha';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00017703.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'Kannada';
        newMovie.genres = ['Action', 'Comedy', 'Thriller'];
        newMovie.location = 'Gopalan Cinemas: Sirsi Circle';
        newMovie.price = '120';
        newMovie.seatInfo = 'PREMIER';
        newMovie.screen = 'SCREEN 3';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030177';
        newMovie.title = '10 Cloverfield Lane';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00039119.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'English';
        newMovie.genres = ['Drama', 'Horror', 'Mystery'];
        newMovie.location = 'Urvashi Digital 4k Cinema: Lalbagh';
        newMovie.price = '200';
        newMovie.seatInfo = 'DIAMOND';
        newMovie.screen = 'AUDI 2';
        movies.push(newMovie);
        newMovie = angular.copy(movie);
        newMovie.id = 'ET00030178';
        newMovie.title = 'Central Intelligence';
        newMovie.imgurl = 'http://172.16.65.3:8009/WebNotifications/Bookmyshow/uploads/ET00036163.jpg';
        newMovie.booknow = '#/payment/' + newMovie.id;
        newMovie.language = 'English';
        newMovie.genres = ['Action', 'Comedy', 'Crime'];
        newMovie.location = 'Q Cinemas: Whitefield, Bengaluru';
        newMovie.price = '200';
        newMovie.seatInfo = 'DIAMOND';
        newMovie.screen = 'AUDI 4';
        movies.push(newMovie);
        return movies;
    };
    this.getMovieDetails = function(movieId) {
        movies = this.getMoviesForBooking();
        var movie = {};
        angular.forEach(movies, function(value, key) {
            if (value && value.id == movieId) {
                movie = value;
            }
        }, movie, movieId);
        return movie;
    };
    this.bookMovie = function(movie) {
        UserNotificationService.notifyBookMovie(movie);
    }
}]);
